#!/usr/bin/env python3
"""
bin2c.py: Convert a binary file to a C source array.
Usage: python3 bin2c.py <input_file> <output_c_file> <symbol_name>
"""

import sys
import os

def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <input_file> <output_c_file> <symbol_name>", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    symbol_name = sys.argv[3]

    if not os.path.isfile(input_path):
        print(f"Error: Input file '{input_path}' not found.", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "rb") as f:
        data = f.read()

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by bin2c.py - DO NOT EDIT */\n")
        f.write("#include <stddef.h>\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const size_t {symbol_name}_size = {len(data)};\n\n")
        f.write(f"__attribute__((aligned(16))) const uint8_t {symbol_name}[] = {{\n")

        line_bytes = []
        for i, b in enumerate(data):
            line_bytes.append(f"0x{b:02x}")
            if len(line_bytes) >= 16:
                f.write("    " + ", ".join(line_bytes) + ",\n")
                line_bytes = []
        if line_bytes:
            f.write("    " + ", ".join(line_bytes) + "\n")

        f.write("};\n")

    print(f"[bin2c] Generated {output_path} ({len(data)} bytes, symbol: {symbol_name})")

if __name__ == "__main__":
    main()
